import { Slider } from '../compontents'

function Home() {
    document.title = "T-Shop | Shop bán quần áo thời trang trẻ em"

    return (
        <main className="main" style={{ minHeight: "100vh" }}>
            <Slider/>
            <h2>Sản phẩm nổi bật</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Velit dolorum, libero, magni doloribus quibusdam qui voluptates modi ipsam illum veniam, cum laborum tempore quia vero maiores recusandae eius non in.
            Inventore quo reprehenderit blanditiis aut dolore at non ipsum earum provident cumque voluptas error vel, dignissimos voluptatibus quidem sequi, praesentium pariatur, aliquam placeat corrupti quibusdam dicta velit necessitatibus maxime. Itaque.
            Reiciendis earum quos dolorum, enim non, ex impedit, consequatur culpa fugit dolores cum beatae alias officiis aperiam minima ut sed dolorem architecto iste quibusdam quasi? Sint corporis quos neque rerum!
            Asperiores aliquid laboriosam, debitis voluptatum, laudantium ex ipsa cupiditate explicabo sed sequi autem ut velit ducimus reiciendis aspernatur nihil. Cum, provident adipisci? Quas exercitationem error hic qui vero officia a.
            Magnam harum tenetur aliquid ducimus perspiciatis, hic voluptatem assumenda magni ipsa, quasi facilis corrupti necessitatibus ratione illum sit quisquam, iste ex explicabo omnis beatae architecto adipisci. Tempora, voluptatem quo! Quas.
            Laborum, porro quasi repellat minima consequatur nisi similique praesentium maxime tenetur. Minima enim excepturi culpa placeat iste in dolorem atque, earum eius vitae voluptas ex veritatis eos sequi cupiditate ab?
            Ad ut odit exercitationem totam voluptate illum pariatur, expedita est, culpa illo amet magnam aspernatur at officia sint ea delectus quasi molestias facilis, possimus esse. Natus sed sapiente esse amet.
            Cupiditate, adipisci harum sed eos fugiat provident sapiente natus labore molestiae at ipsam sint eaque odit incidunt optio magni architecto voluptatem ipsa. Ipsum deleniti soluta odit provident deserunt consequuntur quidem.
            Ullam iste ut repellendus, perspiciatis vitae minus corrupti recusandae, velit exercitationem incidunt, in necessitatibus assumenda id. Illum facilis ipsa quibusdam, consequuntur nostrum, commodi cumque ipsum assumenda voluptas dolores repellat natus.
            Non id asperiores voluptatum quis vel rerum optio iusto explicabo culpa, reiciendis beatae tempora, quidem magni maiores nobis molestias quasi inventore! Quaerat commodi dolore voluptate repellendus illum sequi consequuntur aperiam?
            Reprehenderit voluptate est, qui accusamus doloremque cupiditate quasi praesentium molestias officiis minus perspiciatis corporis esse eius sunt quos corrupti blanditiis adipisci molestiae, nihil dolores eligendi tempore dolorem. Ipsa, autem enim?
            Recusandae provident sapiente incidunt nam aliquid, officiis blanditiis in necessitatibus earum cum assumenda dolores, mollitia obcaecati odio! Dicta sapiente doloremque delectus incidunt quia maxime. Quo quas asperiores quod tempore soluta?
            Deleniti quae, repudiandae atque explicabo libero at provident magnam fuga sapiente nesciunt enim labore iste, nostrum nisi beatae voluptatum fugiat quo eum, tempora impedit odit vero vel sit! Deserunt, ad!
            Inventore, exercitationem? Id, quaerat, unde ex magnam provident doloremque qui, esse possimus quae asperiores quo reprehenderit. Minima obcaecati placeat debitis impedit maiores aperiam, dolorem molestias dicta, repellat ea nobis eveniet.
            Dolorem consectetur quisquam nihil, dolores maiores porro voluptatum iusto autem, delectus asperiores mollitia aliquid error. Quas beatae assumenda illo consequatur dolorum itaque vitae odio? Perspiciatis veritatis dolorem eligendi perferendis quasi.
            Autem, itaque quas sint deleniti quaerat optio culpa reprehenderit quos quam dicta voluptate ipsa, corrupti cupiditate. Odit vitae nihil est, repellat debitis, soluta velit alias eligendi reprehenderit sunt aut magnam.
            Dolorum voluptate aperiam tempore quae laborum corporis reiciendis, at tenetur totam repellendus, magni velit deleniti quis quasi beatae deserunt rem quaerat culpa enim facere non laudantium, provident ipsum doloremque. A.
            Architecto id fugit unde quasi? Maiores, optio minus. Eius dolorum unde dicta! Dolorem, maxime! Error quasi in maxime cum consequuntur aperiam harum, sequi aspernatur facere nesciunt, beatae distinctio, voluptatibus dolorum?
            Et voluptatum veniam quaerat cupiditate nulla at a quo exercitationem impedit placeat nihil ipsam modi eveniet quia, reprehenderit, beatae possimus deserunt illum tempore aliquam. Tempore sapiente eaque voluptas amet iusto!
            Explicabo temporibus fugiat ipsam ratione quaerat quos suscipit sed sunt cum quasi tempore illum ab, quis vel magni nemo non harum nostrum? Nobis ea aspernatur temporibus id harum veritatis minima?
            Deserunt reiciendis, cupiditate iste ipsa distinctio impedit minus obcaecati quam, placeat, incidunt voluptatem illum. Voluptatem minima odit voluptate iste, fugit, veritatis culpa autem dolore, recusandae eos officiis architecto doloribus sit.
            Perspiciatis ad magni, doloremque ipsa ullam vero obcaecati ipsum quisquam possimus repellendus voluptas voluptatibus rerum ratione. Corrupti dolore, deleniti laudantium accusamus at sit, exercitationem non iure, quia laborum fuga? Unde.
            Provident ad tempore modi aspernatur pariatur rerum asperiores autem maiores. Sunt, iste nemo qui quidem veniam temporibus aut iure quo, non quos, dolore beatae nisi eius corrupti reiciendis modi reprehenderit?
            Facilis, ad. Optio eius, sapiente sequi libero quo error! Obcaecati reiciendis id quae distinctio, exercitationem natus fuga nisi laboriosam velit. Eveniet provident nobis hic nesciunt doloremque? Accusamus est recusandae quia!
            Libero modi amet ab at autem, tempora nisi enim? Non tempora optio eveniet temporibus aperiam laborum, esse excepturi ratione qui vitae nesciunt autem culpa maiores debitis omnis ipsum necessitatibus. Eius.
            Error quibusdam molestiae placeat provident quod voluptatibus est amet, reprehenderit atque beatae ex corporis rerum consequatur autem ut adipisci expedita. Porro, fuga perferendis vel eos quasi libero non soluta repudiandae.
            Consectetur quos aliquam iure deleniti molestias sequi, quia dolores voluptate, facilis culpa reiciendis ad ullam asperiores, illum aspernatur sapiente voluptatibus quae incidunt cupiditate aperiam reprehenderit hic ipsa ut. Dolorum, id!
            Quae placeat provident deserunt voluptates culpa fugiat blanditiis officiis, enim non eius aliquid, asperiores amet? Excepturi, eligendi natus ducimus quibusdam cumque voluptatibus quasi quidem eveniet quod accusamus enim ipsam deserunt!
            Est laudantium voluptas vero harum aut exercitationem labore eaque mollitia soluta at eveniet quae, quibusdam omnis rem vitae cumque quod sit accusantium, magni dolores, earum voluptatibus sunt doloribus. Doloremque, magnam.
            Minima blanditiis error est exercitationem itaque quaerat ipsum. Natus quaerat quisquam consectetur, nesciunt delectus eveniet iste beatae ex consequuntur totam sequi placeat nulla quia ipsa ut vero odit obcaecati omnis.
            Ratione exercitationem possimus alias incidunt veritatis quam itaque soluta. Eligendi adipisci at veniam ex numquam maxime. Omnis neque perferendis sunt, sit nisi magnam accusantium pariatur ducimus tempore itaque asperiores sapiente!
            Pariatur cumque, doloremque expedita alias aliquam id. Deserunt rem tempore tempora, eum commodi non sint dolorem aliquid asperiores voluptas eaque eius illo eligendi eveniet et placeat. Quibusdam culpa quis cumque?
            Saepe doloremque incidunt maiores, odit deleniti exercitationem non cum blanditiis tempora minus eveniet ducimus ad unde odio quibusdam officiis facilis magni dolores qui quasi quidem. Quas velit sunt suscipit itaque.
            Accusamus error perferendis eum consequatur rem quaerat, non corrupti adipisci, asperiores eos sed quod molestiae voluptatum cumque doloribus voluptatem necessitatibus, odio amet deleniti animi modi ut laudantium dicta facilis? Veritatis.
            Blanditiis illum, esse, consequatur libero explicabo provident praesentium tempora exercitationem facilis eaque, pariatur quae cupiditate vel cum animi odit. Tempora ullam nesciunt atque. Quam rem aspernatur veritatis architecto aperiam impedit?
            Facilis error, deserunt, veniam similique nobis odit rem nesciunt tempora sunt neque exercitationem voluptate sequi incidunt perferendis minus, repellat quaerat esse ullam suscipit consequuntur aliquam. Adipisci soluta omnis neque esse?
            Eveniet, suscipit, assumenda laborum earum illo maxime quam minus dicta quia eaque perspiciatis cupiditate accusamus labore reiciendis dolore fugiat minima voluptas alias amet! Eaque architecto pariatur consequuntur debitis officia qui.
            Rerum, omnis reprehenderit? Laborum aperiam fuga necessitatibus iste enim sunt dolores distinctio quisquam, suscipit corrupti, doloribus odit ipsam aut maxime praesentium. Maiores ratione nam placeat, est aut et doloribus odio?
            Tempora distinctio corporis vitae praesentium omnis expedita maxime laudantium quaerat, voluptas quibusdam debitis sunt quis voluptates, culpa officia quas recusandae natus adipisci nobis molestias hic, ipsum doloribus. Veritatis, in eius.
            Nostrum quasi dolorum adipisci ea! Quasi, vel dolor in blanditiis dolorem sed quidem, recusandae amet molestiae, quia totam? Ipsum vitae temporibus porro delectus pariatur blanditiis animi aliquid repellat accusamus suscipit.
            Tempore provident voluptates quisquam minima odit, aspernatur harum libero magni, eius temporibus a repudiandae nesciunt unde asperiores culpa laudantium optio nulla totam esse at sapiente ipsum accusantium. Voluptas, a commodi.
            Nostrum natus inventore, quas iusto, voluptatibus odio quaerat recusandae id blanditiis ipsam explicabo aut omnis, itaque esse assumenda veritatis. Voluptas nisi eum non rerum consectetur excepturi fuga, consequuntur necessitatibus numquam.
            Omnis explicabo quisquam doloribus, eaque consequuntur quaerat deleniti debitis necessitatibus obcaecati sapiente exercitationem ipsa voluptatibus nemo temporibus eveniet quo, veniam vero esse aliquam est quis earum. Nulla quis eius fugit?
            Harum odit perspiciatis eum voluptate debitis blanditiis labore, doloribus earum ipsam enim qui, et nostrum? Inventore officia sit voluptatum quasi aliquam id, porro eos natus architecto ratione ipsa labore exercitationem.
            Animi, perferendis! Inventore esse sint saepe, odit quia assumenda explicabo in id! Iusto consequuntur eius reprehenderit sed, corporis quaerat itaque id dolorem at illo beatae, ex, voluptas perferendis dolores quis.
            Reprehenderit itaque, sint temporibus et consectetur a ipsa accusantium ab eius mollitia sapiente explicabo possimus. Dolorem odit illum, fuga eligendi ipsam pariatur consectetur exercitationem optio dolorum nisi perspiciatis quod quaerat!
            Neque dolorem deserunt iusto minima commodi itaque voluptate voluptatum quidem incidunt molestiae, necessitatibus praesentium impedit eius, nesciunt aspernatur aut ab, nulla optio reprehenderit ad veritatis soluta. Est pariatur saepe suscipit.
            Tempora vitae officia deserunt. Officia nihil tempora eum deleniti tempore debitis dolore ex consequuntur expedita odit ducimus ullam, a consequatur repudiandae? Reprehenderit pariatur voluptatum debitis, velit autem dolorem maiores tempora!
            Consectetur nam dolor voluptatum nihil quis dolorem, soluta nisi inventore nostrum ea natus recusandae quos in molestias quidem facere sapiente eaque amet eum! Distinctio voluptate mollitia pariatur repudiandae tempora illo.
            A ea culpa molestias sapiente rerum exercitationem aspernatur quia sequi, eligendi totam modi. Repellat, modi explicabo vel natus molestias tempore laboriosam ex facere voluptates nihil accusamus, ipsam nam consequuntur nulla.
            Distinctio rem commodi corporis possimus maxime quia, accusantium modi porro numquam aut at non, laudantium magni natus velit a, tempore placeat dolor. Ullam natus consequuntur vero dicta enim aspernatur odit.
            Nam libero natus impedit sequi expedita, ut veritatis quis, voluptas illum dicta autem cupiditate perspiciatis modi iure quia earum error odit rem, molestiae velit pariatur quos amet. Soluta, recusandae amet.
            Distinctio praesentium incidunt optio blanditiis iure doloremque. Iure, itaque necessitatibus. Quia aliquam facere sint commodi iusto error vel, provident quod atque natus, quibusdam perferendis quo incidunt temporibus suscipit repudiandae quae?
            Cumque quam rerum, dolores perspiciatis ullam dolore in. Consectetur accusamus, odio rerum qui labore voluptatum facilis. Maxime mollitia quaerat dolorum rerum nobis a nihil impedit, tenetur adipisci, perferendis, eligendi laborum.
            Assumenda voluptate vel qui! Neque, fugit labore amet veritatis facilis iure id. Sed quam nihil quas odio deleniti porro, omnis velit, quae ea labore, ut laboriosam. Ea ipsa quibusdam libero?
            Maiores accusamus officiis odit repellendus sapiente pariatur numquam facilis vero laudantium nisi ipsam hic, porro harum qui soluta, sed commodi debitis, aut ad esse quae dicta? Quae nam officiis magnam?
            Aperiam at quod iure doloribus illum, eaque ad rerum dolor mollitia nesciunt voluptatem ipsam quae cumque debitis. Officia, dolore! Impedit maiores ipsa nostrum obcaecati ad eaque nam corporis fugiat cumque?
            Minus aut, reiciendis in saepe a quis ipsam laudantium adipisci, qui deserunt sequi veritatis ut quae tempore doloremque? Animi recusandae eveniet corrupti nostrum earum quisquam nulla, repudiandae iure a praesentium.
            Reprehenderit in animi doloremque a non doloribus quidem laborum tempore, quas perferendis possimus nemo obcaecati corporis dolores assumenda veritatis natus aut dignissimos sint quibusdam neque at illum voluptatem officia? Praesentium?
            Quidem adipisci sint eius ex tempora est assumenda eos similique, porro libero molestias rerum perspiciatis fuga asperiores laborum voluptatibus delectus. Dicta assumenda vero non. Sint labore consequuntur officia cum dolores?
            Quod eius labore rem nisi sit laborum reprehenderit vitae, commodi deserunt nihil. Repudiandae consectetur nesciunt debitis beatae consequuntur. Nisi temporibus, enim dicta aperiam recusandae doloremque provident debitis dolore officia maxime.
            Ipsam maxime necessitatibus obcaecati accusantium adipisci quod, temporibus officiis odio veniam earum! Iusto temporibus ea omnis, distinctio laboriosam illo velit atque quam quidem delectus quae dolor hic. Nobis, totam distinctio.
            Voluptate iste magnam magni obcaecati! Delectus aliquam, laudantium minus aliquid hic animi facere aspernatur ab facilis reprehenderit. Aperiam, rerum repudiandae in numquam maxime animi atque iusto voluptatem quia. Eum, placeat.
            Sunt, omnis reprehenderit! Delectus voluptates sint velit rem ratione amet illum enim quod quos dolores! Quia velit provident distinctio, voluptatem et dolores ut illum repudiandae consequatur enim eos deleniti corporis!
            Ex, nobis iure eveniet iusto rem possimus eaque veniam quasi aut enim doloremque non, dolores sapiente ad minima cum. Aliquid consequatur similique, placeat voluptatum inventore autem quaerat? Earum, repellendus quos.
            Veritatis expedita cumque similique fuga provident, architecto quam, quos, illum in exercitationem temporibus odit ab eveniet possimus porro aliquam? Quo veniam illo consequuntur itaque blanditiis ipsam suscipit iusto delectus at?
            Esse necessitatibus cupiditate tenetur ex maiores voluptas debitis! Enim, deserunt repellat omnis explicabo repellendus itaque exercitationem praesentium. Tempora ducimus assumenda omnis placeat veniam quas laboriosam rem quis, nemo quisquam debitis.
            Magnam soluta deserunt iure ab consequuntur vero id, corporis eos reprehenderit asperiores laboriosam sint quasi unde quod ratione quaerat illum rerum aspernatur sequi aliquam praesentium obcaecati! Veniam fuga temporibus placeat.
            Exercitationem ut ducimus, facilis provident sequi voluptas aperiam debitis minus odit repellat id placeat, corporis rem consectetur magni cupiditate veniam iure quod in illo omnis perspiciatis, a porro explicabo? Nihil?
            Saepe quaerat necessitatibus aut natus eum? Molestias nisi unde, minima molestiae numquam labore dolorem sapiente quia voluptatibus odit nulla possimus, aspernatur tempora! Maiores et nulla exercitationem, minus corrupti omnis adipisci.
            Necessitatibus est distinctio quaerat nulla. In, doloremque! Placeat, repellat aperiam? Assumenda eius, temporibus impedit modi sunt exercitationem magni maiores, facere perspiciatis adipisci alias libero hic, eos officia commodi incidunt ipsam?
            Quaerat tempore adipisci odio. Ducimus dolorum perspiciatis, maiores voluptatem consequuntur, soluta, cupiditate exercitationem iusto accusantium eligendi error veniam eos. Dicta minus non cum incidunt neque quae perferendis ipsa consequatur inventore.
            Eaque cum, adipisci soluta voluptate accusantium quos explicabo recusandae necessitatibus repellat voluptatum eligendi vel vitae expedita ad reiciendis, enim quisquam repudiandae tenetur inventore! Omnis soluta minus hic delectus aperiam neque!
            Vero sequi magnam sunt cupiditate minima voluptatem aliquid ducimus iure autem nihil aperiam consequuntur omnis aliquam quod, quisquam officia perspiciatis tempora porro! Ad pariatur quidem, obcaecati explicabo optio fugiat voluptates.
            Vel nostrum perspiciatis adipisci voluptas molestiae quae vitae ex architecto eligendi modi! Voluptatibus ex magni earum quo. Dolor inventore unde minus? Placeat soluta blanditiis perferendis minus magnam architecto aliquam. Suscipit!
            Ratione fuga beatae sit. Laboriosam delectus, ex hic a asperiores, voluptatem doloribus officiis quibusdam nam aliquid qui reprehenderit deleniti quaerat voluptates eum est? Labore rem architecto iure! Blanditiis, vitae id.
            Facere quis harum odit nostrum corporis reprehenderit, vero blanditiis pariatur quod, ex, in accusamus. Praesentium suscipit dolore tempora maxime, cumque, quam harum magnam porro temporibus aspernatur quisquam? Veniam, veritatis eligendi!
            Harum repudiandae nisi obcaecati fugiat a dicta. Deleniti dolorum natus in iste ipsa quo delectus dolores harum consectetur soluta, veritatis magni esse ratione voluptatum quibusdam dolor perspiciatis ea quisquam minus!
            Rerum ab incidunt, dolores aliquam distinctio reprehenderit corrupti aspernatur. Minus, harum. Sequi, alias? Quisquam non quis itaque! Qui neque porro quidem voluptatibus, vitae commodi iste harum, fugiat earum iure voluptatum?
            Voluptas quam adipisci assumenda maiores sequi at nobis tempore consectetur suscipit possimus? Eveniet libero ipsam consequatur maiores a soluta repudiandae cumque dignissimos veniam, laborum, voluptatem unde. Asperiores nobis maiores esse.
            Eius, odit? Quaerat possimus exercitationem illo beatae, voluptas porro quis minus laboriosam facilis doloribus sed ad repudiandae, iste accusamus. Impedit, iusto provident? Adipisci ad voluptatem eos alias, odio quo distinctio.
            Assumenda error commodi tempore atque minima expedita et aspernatur, facere at voluptatum accusantium numquam, voluptates cupiditate dignissimos illo architecto iusto earum voluptas suscipit natus quaerat similique libero laborum! Beatae, magnam!
            Tempore, dolore laboriosam similique labore placeat vero minima cum reprehenderit modi rerum, possimus cupiditate voluptas nam, asperiores veniam repellat natus optio illum consectetur accusamus amet. Fuga libero reprehenderit maiores repellat.
            Suscipit illum ea pariatur, odio sint dolores aliquam, magni impedit obcaecati laboriosam commodi. Officia sint animi libero reprehenderit odio? Sapiente exercitationem fugiat omnis sequi maxime amet quo eos natus. Vel?
            Corrupti asperiores, necessitatibus maiores praesentium minus hic deleniti alias facilis! Officia quas excepturi ullam eos, pariatur culpa porro animi quae. Maxime harum tempore expedita maiores quos adipisci, natus eveniet vel.
            Dignissimos distinctio facilis expedita, quia minima beatae perferendis quas. Voluptatem praesentium pariatur libero fugiat fuga perspiciatis odio rem recusandae esse ipsum officia, magnam exercitationem in autem sit dolore velit necessitatibus.
            Laudantium quos veniam tenetur quisquam eligendi reiciendis distinctio, iusto doloribus earum reprehenderit soluta laboriosam hic voluptatibus neque esse at rerum nesciunt! Sit voluptatem doloremque, fuga placeat commodi dicta eius obcaecati.
            Sint pariatur ipsa iusto vitae, perspiciatis nam? Provident eum nam facere. Culpa consequuntur explicabo itaque ratione, officiis accusantium sint eius, consequatur sunt, unde quam molestias. Ratione culpa ut eligendi corporis?
            Doloremque quos, beatae similique temporibus minus ipsa voluptatum quasi reprehenderit quisquam aliquam in quibusdam consequuntur ut rem earum commodi ea aut, fugiat, optio dolor? Dolore eveniet sint fuga error quae!
            Illum minus adipisci, cum itaque dolorem assumenda hic corrupti esse consequatur quo quibusdam veniam nobis totam magni facere vero sequi neque recusandae rem porro. At harum voluptatem accusantium obcaecati aut?
            Similique nisi, tempora voluptate quam eum soluta quasi molestiae fugiat animi reprehenderit atque necessitatibus quia aliquid voluptates, et sit iusto sequi illum officia? Suscipit accusantium repellendus, asperiores explicabo inventore cum!
            Eaque commodi soluta quidem nostrum fuga, voluptatem voluptatibus a ipsam ipsum assumenda, obcaecati vero ex pariatur laborum nam illum mollitia numquam rem perferendis. Ullam, nihil mollitia soluta assumenda doloremque minus.
            Accusantium at aliquam, quos necessitatibus architecto nostrum reprehenderit modi recusandae reiciendis? Quam ab quo laudantium nesciunt non autem sunt quibusdam quisquam repellendus. Aliquam hic similique minima, corporis quas reiciendis doloribus.
            Repudiandae quia veritatis voluptas maiores, odit illo nulla accusamus porro soluta numquam corrupti aliquam facilis rem quas, veniam pariatur? Optio minima earum recusandae quo deleniti autem, consequuntur cumque sapiente culpa!
            Perspiciatis odio corporis beatae obcaecati nulla, expedita ad sunt animi, quia minima nihil? Tempora, nobis sint, ratione magni modi voluptate hic commodi aperiam magnam minima rem id quia, maxime quo.
            Voluptates, voluptatem corrupti corporis laborum harum, maxime itaque ad ipsam nostrum sapiente quas architecto beatae cum aliquam nam nihil non eos pariatur quam enim sunt, aspernatur est. Debitis, hic odit?
            Iure distinctio eius reprehenderit maxime aperiam amet cumque quia id illo quidem enim, odit dolor adipisci aut harum. Distinctio nesciunt inventore natus animi cumque, unde laborum ea esse dolore eius.
            Iusto numquam iste obcaecati voluptatum minus, ratione illo quisquam autem eligendi dolorum consectetur minima perspiciatis, voluptatem, omnis perferendis at. Animi repellendus reiciendis tenetur eos exercitationem temporibus explicabo eligendi vitae ipsa.
            Est voluptate facere excepturi tenetur amet sunt temporibus ad molestias aspernatur modi labore accusantium atque dignissimos distinctio ullam adipisci ipsam laboriosam quidem, odit quia. Saepe ipsam libero voluptas explicabo dolorem.
            Suscipit perspiciatis dicta numquam at, ipsa quas perferendis in necessitatibus corporis ad similique facilis iste rem mollitia. Magnam maiores dolorem autem repellat rerum labore tenetur minima officia, enim facere! Corporis!
            </p>
        </main>
    )
}

export default Home